export const CREATE_MOVIE = 'CREATE_MOVIE';
export const FETCH_MOVIES = 'FETCH_MOVIES';
export const FETCH_MOVIE = 'FETCH_MOVIE';
export const UPDATE_MOVIE = 'UPDATE_MOVIE';
export const DELETE_MOVIE = 'DELETE_MOVIE';
export const FETCH_BOOKED_SEATS = 'FETCH_BOOKED_SEATS';
export const FETCH_BOOKED_SEATS_ERROR = 'FETCH_BOOKED_SEATS_ERROR';
export const MOVIE_ERROR = 'MOVIE_ERROR';
